// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	scheme "github.com/chaos-mesh/chaos-mesh/pkg/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodchaosGetter has a method to return a PodChaosInterface.
// A group's client should implement this interface.
type PodchaosGetter interface {
	Podchaos(namespace string) PodChaosInterface
}

// PodChaosInterface has methods to work with PodChaos resources.
type PodChaosInterface interface {
	Create(ctx context.Context, podChaos *apiv1alpha1.PodChaos, opts v1.CreateOptions) (*apiv1alpha1.PodChaos, error)
	Update(ctx context.Context, podChaos *apiv1alpha1.PodChaos, opts v1.UpdateOptions) (*apiv1alpha1.PodChaos, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podChaos *apiv1alpha1.PodChaos, opts v1.UpdateOptions) (*apiv1alpha1.PodChaos, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.PodChaos, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.PodChaosList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.PodChaos, err error)
	PodChaosExpansion
}

// podchaos implements PodChaosInterface
type podchaos struct {
	*gentype.ClientWithList[*apiv1alpha1.PodChaos, *apiv1alpha1.PodChaosList]
}

// newPodchaos returns a Podchaos
func newPodchaos(c *ApiV1alpha1Client, namespace string) *podchaos {
	return &podchaos{
		gentype.NewClientWithList[*apiv1alpha1.PodChaos, *apiv1alpha1.PodChaosList](
			"podchaos",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.PodChaos { return &apiv1alpha1.PodChaos{} },
			func() *apiv1alpha1.PodChaosList { return &apiv1alpha1.PodChaosList{} },
		),
	}
}
