// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	scheme "github.com/chaos-mesh/chaos-mesh/pkg/client/versioned/scheme"
)

// PodhttpchaosGetter has a method to return a PodHttpChaosInterface.
// A group's client should implement this interface.
type PodhttpchaosGetter interface {
	Podhttpchaos(namespace string) PodHttpChaosInterface
}

// PodHttpChaosInterface has methods to work with PodHttpChaos resources.
type PodHttpChaosInterface interface {
	Create(ctx context.Context, podHttpChaos *apiv1alpha1.PodHttpChaos, opts v1.CreateOptions) (*apiv1alpha1.PodHttpChaos, error)
	Update(ctx context.Context, podHttpChaos *apiv1alpha1.PodHttpChaos, opts v1.UpdateOptions) (*apiv1alpha1.PodHttpChaos, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podHttpChaos *apiv1alpha1.PodHttpChaos, opts v1.UpdateOptions) (*apiv1alpha1.PodHttpChaos, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.PodHttpChaos, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.PodHttpChaosList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.PodHttpChaos, err error)
	PodHttpChaosExpansion
}

// podhttpchaos implements PodHttpChaosInterface
type podhttpchaos struct {
	*gentype.ClientWithList[*apiv1alpha1.PodHttpChaos, *apiv1alpha1.PodHttpChaosList]
}

// newPodhttpchaos returns a Podhttpchaos
func newPodhttpchaos(c *ApiV1alpha1Client, namespace string) *podhttpchaos {
	return &podhttpchaos{
		gentype.NewClientWithList[*apiv1alpha1.PodHttpChaos, *apiv1alpha1.PodHttpChaosList](
			"podhttpchaos",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.PodHttpChaos { return &apiv1alpha1.PodHttpChaos{} },
			func() *apiv1alpha1.PodHttpChaosList { return &apiv1alpha1.PodHttpChaosList{} },
		),
	}
}
