// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	scheme "github.com/chaos-mesh/chaos-mesh/pkg/client/versioned/scheme"
)

// PodnetworkchaosGetter has a method to return a PodNetworkChaosInterface.
// A group's client should implement this interface.
type PodnetworkchaosGetter interface {
	Podnetworkchaos(namespace string) PodNetworkChaosInterface
}

// PodNetworkChaosInterface has methods to work with PodNetworkChaos resources.
type PodNetworkChaosInterface interface {
	Create(ctx context.Context, podNetworkChaos *apiv1alpha1.PodNetworkChaos, opts v1.CreateOptions) (*apiv1alpha1.PodNetworkChaos, error)
	Update(ctx context.Context, podNetworkChaos *apiv1alpha1.PodNetworkChaos, opts v1.UpdateOptions) (*apiv1alpha1.PodNetworkChaos, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podNetworkChaos *apiv1alpha1.PodNetworkChaos, opts v1.UpdateOptions) (*apiv1alpha1.PodNetworkChaos, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.PodNetworkChaos, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.PodNetworkChaosList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.PodNetworkChaos, err error)
	PodNetworkChaosExpansion
}

// podnetworkchaos implements PodNetworkChaosInterface
type podnetworkchaos struct {
	*gentype.ClientWithList[*apiv1alpha1.PodNetworkChaos, *apiv1alpha1.PodNetworkChaosList]
}

// newPodnetworkchaos returns a Podnetworkchaos
func newPodnetworkchaos(c *ApiV1alpha1Client, namespace string) *podnetworkchaos {
	return &podnetworkchaos{
		gentype.NewClientWithList[*apiv1alpha1.PodNetworkChaos, *apiv1alpha1.PodNetworkChaosList](
			"podnetworkchaos",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.PodNetworkChaos { return &apiv1alpha1.PodNetworkChaos{} },
			func() *apiv1alpha1.PodNetworkChaosList { return &apiv1alpha1.PodNetworkChaosList{} },
		),
	}
}
