# Generated by ./cmd/generate-makefile. DO NOT EDIT.

##@ Generated targets in binary.generated.mk

.PHONY: images/chaos-mesh/bin/chaos-controller-manager
images/chaos-mesh/bin/chaos-controller-manager: SHELL:=$(RUN_IN_BUILD_SHELL)
images/chaos-mesh/bin/chaos-controller-manager: image-build-env  ## Build binary chaos-controller-manager
	$(GO) build -ldflags "$(LDFLAGS)" -tags "${BUILD_TAGS}" -o images/chaos-mesh/bin/chaos-controller-manager cmd/chaos-controller-manager/main.go

.PHONY: images/chaos-daemon/bin/chaos-daemon
images/chaos-daemon/bin/chaos-daemon: SHELL:=$(RUN_IN_BUILD_SHELL)
images/chaos-daemon/bin/chaos-daemon: image-build-env pkg/time/fakeclock/fake_clock_gettime.o pkg/time/fakeclock/fake_gettimeofday.o ## Build binary chaos-daemon
	$(CGO) build -ldflags "$(LDFLAGS)" -tags "${BUILD_TAGS}" -o images/chaos-daemon/bin/chaos-daemon cmd/chaos-daemon/main.go

.PHONY: images/chaos-dashboard/bin/chaos-dashboard
images/chaos-dashboard/bin/chaos-dashboard: SHELL:=$(RUN_IN_BUILD_SHELL)
images/chaos-dashboard/bin/chaos-dashboard: image-build-env ui ## Build binary chaos-dashboard
	$(CGO) build -ldflags "$(LDFLAGS)" -tags "${BUILD_TAGS}" -o images/chaos-dashboard/bin/chaos-dashboard cmd/chaos-dashboard/main.go

.PHONY: images/chaos-daemon/bin/cdh
images/chaos-daemon/bin/cdh: SHELL:=$(RUN_IN_BUILD_SHELL)
images/chaos-daemon/bin/cdh: image-build-env  ## Build binary chaos-daemon-helper
	$(CGO) build -ldflags "$(LDFLAGS)" -tags "${BUILD_TAGS}" -o images/chaos-daemon/bin/cdh cmd/chaos-daemon-helper/main.go

.PHONY: clean-binary
clean-binary:
	rm -f images/chaos-mesh/bin/chaos-controller-manager
	rm -f images/chaos-daemon/bin/chaos-daemon
	rm -f images/chaos-dashboard/bin/chaos-dashboard
	rm -f images/chaos-daemon/bin/cdh
