apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: web-show-pod-failure
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "web-show"
  scheduler:
    cron: "@every 2m"
