// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/pkg/client/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePodnetworkchaos implements PodNetworkChaosInterface
type fakePodnetworkchaos struct {
	*gentype.FakeClientWithList[*v1alpha1.PodNetworkChaos, *v1alpha1.PodNetworkChaosList]
	Fake *FakeApiV1alpha1
}

func newFakePodnetworkchaos(fake *FakeApiV1alpha1, namespace string) apiv1alpha1.PodNetworkChaosInterface {
	return &fakePodnetworkchaos{
		gentype.NewFakeClientWithList[*v1alpha1.PodNetworkChaos, *v1alpha1.PodNetworkChaosList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("podnetworkchaos"),
			v1alpha1.SchemeGroupVersion.WithKind("PodNetworkChaos"),
			func() *v1alpha1.PodNetworkChaos { return &v1alpha1.PodNetworkChaos{} },
			func() *v1alpha1.PodNetworkChaosList { return &v1alpha1.PodNetworkChaosList{} },
			func(dst, src *v1alpha1.PodNetworkChaosList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PodNetworkChaosList) []*v1alpha1.PodNetworkChaos {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PodNetworkChaosList, items []*v1alpha1.PodNetworkChaos) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
