// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	chaosmeshapiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	internalinterfaces "github.com/chaos-mesh/chaos-mesh/pkg/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/pkg/client/listers/api/v1alpha1"
	versioned "github.com/chaos-mesh/chaos-mesh/pkg/client/versioned"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodNetworkChaosInformer provides access to a shared informer and lister for
// Podnetworkchaos.
type PodNetworkChaosInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.PodNetworkChaosLister
}

type podNetworkChaosInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodNetworkChaosInformer constructs a new informer for PodNetworkChaos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodNetworkChaosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodNetworkChaosInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodNetworkChaosInformer constructs a new informer for PodNetworkChaos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodNetworkChaosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Podnetworkchaos(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Podnetworkchaos(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Podnetworkchaos(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1alpha1().Podnetworkchaos(namespace).Watch(ctx, options)
			},
		},
		&chaosmeshapiv1alpha1.PodNetworkChaos{},
		resyncPeriod,
		indexers,
	)
}

func (f *podNetworkChaosInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodNetworkChaosInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podNetworkChaosInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&chaosmeshapiv1alpha1.PodNetworkChaos{}, f.defaultInformer)
}

func (f *podNetworkChaosInformer) Lister() apiv1alpha1.PodNetworkChaosLister {
	return apiv1alpha1.NewPodNetworkChaosLister(f.Informer().GetIndexer())
}
