/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	pingcapcomv1alpha1 "github.com/pingcap/chaos-operator/pkg/apis/pingcap.com/v1alpha1"
	versioned "github.com/pingcap/chaos-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/pingcap/chaos-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/pingcap/chaos-operator/pkg/client/listers/pingcap.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NetworkChaosInformer provides access to a shared informer and lister for
// NetworkChaoses.
type NetworkChaosInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NetworkChaosLister
}

type networkChaosInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNetworkChaosInformer constructs a new informer for NetworkChaos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNetworkChaosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNetworkChaosInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNetworkChaosInformer constructs a new informer for NetworkChaos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNetworkChaosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PingcapV1alpha1().NetworkChaoses(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PingcapV1alpha1().NetworkChaoses(namespace).Watch(options)
			},
		},
		&pingcapcomv1alpha1.NetworkChaos{},
		resyncPeriod,
		indexers,
	)
}

func (f *networkChaosInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNetworkChaosInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *networkChaosInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pingcapcomv1alpha1.NetworkChaos{}, f.defaultInformer)
}

func (f *networkChaosInformer) Lister() v1alpha1.NetworkChaosLister {
	return v1alpha1.NewNetworkChaosLister(f.Informer().GetIndexer())
}
