// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: ./model/template/serial.go

// Package mock_template is a generated GoMock package.
package mock_template

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	template "github.com/chaos-mesh/chaos-mesh/pkg/workflow/model/template"
)

// MockSerialTemplate is a mock of SerialTemplate interface.
type MockSerialTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockSerialTemplateMockRecorder
}

// MockSerialTemplateMockRecorder is the mock recorder for MockSerialTemplate.
type MockSerialTemplateMockRecorder struct {
	mock *MockSerialTemplate
}

// NewMockSerialTemplate creates a new mock instance.
func NewMockSerialTemplate(ctrl *gomock.Controller) *MockSerialTemplate {
	mock := &MockSerialTemplate{ctrl: ctrl}
	mock.recorder = &MockSerialTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSerialTemplate) EXPECT() *MockSerialTemplateMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockSerialTemplate) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSerialTemplateMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSerialTemplate)(nil).Name))
}

// SerialChildrenList mocks base method.
func (m *MockSerialTemplate) SerialChildrenList() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SerialChildrenList")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SerialChildrenList indicates an expected call of SerialChildrenList.
func (mr *MockSerialTemplateMockRecorder) SerialChildrenList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SerialChildrenList", reflect.TypeOf((*MockSerialTemplate)(nil).SerialChildrenList))
}

// TemplateType mocks base method.
func (m *MockSerialTemplate) TemplateType() template.TemplateType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TemplateType")
	ret0, _ := ret[0].(template.TemplateType)
	return ret0
}

// TemplateType indicates an expected call of TemplateType.
func (mr *MockSerialTemplateMockRecorder) TemplateType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TemplateType", reflect.TypeOf((*MockSerialTemplate)(nil).TemplateType))
}
