// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodIOChaosLister helps list Podiochaos.
// All objects returned here must be treated as read-only.
type PodIOChaosLister interface {
	// List lists all Podiochaos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.PodIOChaos, err error)
	// Podiochaos returns an object that can list and get Podiochaos.
	Podiochaos(namespace string) PodIOChaosNamespaceLister
	PodIOChaosListerExpansion
}

// podIOChaosLister implements the PodIOChaosLister interface.
type podIOChaosLister struct {
	listers.ResourceIndexer[*apiv1alpha1.PodIOChaos]
}

// NewPodIOChaosLister returns a new PodIOChaosLister.
func NewPodIOChaosLister(indexer cache.Indexer) PodIOChaosLister {
	return &podIOChaosLister{listers.New[*apiv1alpha1.PodIOChaos](indexer, apiv1alpha1.Resource("podiochaos"))}
}

// Podiochaos returns an object that can list and get Podiochaos.
func (s *podIOChaosLister) Podiochaos(namespace string) PodIOChaosNamespaceLister {
	return podIOChaosNamespaceLister{listers.NewNamespaced[*apiv1alpha1.PodIOChaos](s.ResourceIndexer, namespace)}
}

// PodIOChaosNamespaceLister helps list and get Podiochaos.
// All objects returned here must be treated as read-only.
type PodIOChaosNamespaceLister interface {
	// List lists all Podiochaos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.PodIOChaos, err error)
	// Get retrieves the PodIOChaos from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.PodIOChaos, error)
	PodIOChaosNamespaceListerExpansion
}

// podIOChaosNamespaceLister implements the PodIOChaosNamespaceLister
// interface.
type podIOChaosNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.PodIOChaos]
}
