// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodNetworkChaosLister helps list Podnetworkchaos.
// All objects returned here must be treated as read-only.
type PodNetworkChaosLister interface {
	// List lists all Podnetworkchaos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.PodNetworkChaos, err error)
	// Podnetworkchaos returns an object that can list and get Podnetworkchaos.
	Podnetworkchaos(namespace string) PodNetworkChaosNamespaceLister
	PodNetworkChaosListerExpansion
}

// podNetworkChaosLister implements the PodNetworkChaosLister interface.
type podNetworkChaosLister struct {
	listers.ResourceIndexer[*apiv1alpha1.PodNetworkChaos]
}

// NewPodNetworkChaosLister returns a new PodNetworkChaosLister.
func NewPodNetworkChaosLister(indexer cache.Indexer) PodNetworkChaosLister {
	return &podNetworkChaosLister{listers.New[*apiv1alpha1.PodNetworkChaos](indexer, apiv1alpha1.Resource("podnetworkchaos"))}
}

// Podnetworkchaos returns an object that can list and get Podnetworkchaos.
func (s *podNetworkChaosLister) Podnetworkchaos(namespace string) PodNetworkChaosNamespaceLister {
	return podNetworkChaosNamespaceLister{listers.NewNamespaced[*apiv1alpha1.PodNetworkChaos](s.ResourceIndexer, namespace)}
}

// PodNetworkChaosNamespaceLister helps list and get Podnetworkchaos.
// All objects returned here must be treated as read-only.
type PodNetworkChaosNamespaceLister interface {
	// List lists all Podnetworkchaos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.PodNetworkChaos, err error)
	// Get retrieves the PodNetworkChaos from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.PodNetworkChaos, error)
	PodNetworkChaosNamespaceListerExpansion
}

// podNetworkChaosNamespaceLister implements the PodNetworkChaosNamespaceLister
// interface.
type podNetworkChaosNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.PodNetworkChaos]
}
