// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// StressChaosLister helps list Stresschaos.
// All objects returned here must be treated as read-only.
type StressChaosLister interface {
	// List lists all Stresschaos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.StressChaos, err error)
	// Stresschaos returns an object that can list and get Stresschaos.
	Stresschaos(namespace string) StressChaosNamespaceLister
	StressChaosListerExpansion
}

// stressChaosLister implements the StressChaosLister interface.
type stressChaosLister struct {
	listers.ResourceIndexer[*apiv1alpha1.StressChaos]
}

// NewStressChaosLister returns a new StressChaosLister.
func NewStressChaosLister(indexer cache.Indexer) StressChaosLister {
	return &stressChaosLister{listers.New[*apiv1alpha1.StressChaos](indexer, apiv1alpha1.Resource("stresschaos"))}
}

// Stresschaos returns an object that can list and get Stresschaos.
func (s *stressChaosLister) Stresschaos(namespace string) StressChaosNamespaceLister {
	return stressChaosNamespaceLister{listers.NewNamespaced[*apiv1alpha1.StressChaos](s.ResourceIndexer, namespace)}
}

// StressChaosNamespaceLister helps list and get Stresschaos.
// All objects returned here must be treated as read-only.
type StressChaosNamespaceLister interface {
	// List lists all Stresschaos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.StressChaos, err error)
	// Get retrieves the StressChaos from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.StressChaos, error)
	StressChaosNamespaceListerExpansion
}

// stressChaosNamespaceLister implements the StressChaosNamespaceLister
// interface.
type stressChaosNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.StressChaos]
}
