// Copyright Chaos Mesh Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TimeChaosLister helps list Timechaos.
// All objects returned here must be treated as read-only.
type TimeChaosLister interface {
	// List lists all Timechaos in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.TimeChaos, err error)
	// Timechaos returns an object that can list and get Timechaos.
	Timechaos(namespace string) TimeChaosNamespaceLister
	TimeChaosListerExpansion
}

// timeChaosLister implements the TimeChaosLister interface.
type timeChaosLister struct {
	listers.ResourceIndexer[*apiv1alpha1.TimeChaos]
}

// NewTimeChaosLister returns a new TimeChaosLister.
func NewTimeChaosLister(indexer cache.Indexer) TimeChaosLister {
	return &timeChaosLister{listers.New[*apiv1alpha1.TimeChaos](indexer, apiv1alpha1.Resource("timechaos"))}
}

// Timechaos returns an object that can list and get Timechaos.
func (s *timeChaosLister) Timechaos(namespace string) TimeChaosNamespaceLister {
	return timeChaosNamespaceLister{listers.NewNamespaced[*apiv1alpha1.TimeChaos](s.ResourceIndexer, namespace)}
}

// TimeChaosNamespaceLister helps list and get Timechaos.
// All objects returned here must be treated as read-only.
type TimeChaosNamespaceLister interface {
	// List lists all Timechaos in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.TimeChaos, err error)
	// Get retrieves the TimeChaos from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.TimeChaos, error)
	TimeChaosNamespaceListerExpansion
}

// timeChaosNamespaceLister implements the TimeChaosNamespaceLister
// interface.
type timeChaosNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.TimeChaos]
}
