apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-duplicate-example
  namespace: chaos-testing
spec:
  action: duplicate
  mode: one
  selector:
    namespaces:
      - tidb-cluster-demo
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  duplicate:
    duplicate: "40"
    correlation: "25"
  duration: "10s"
  scheduler:
    cron: "@every 15s"