name: Release helm chart files

on:
  push:
    tags:
      - "chart-*"

permissions: read-all

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: extract_version
        run: |
          VERSION=${GITHUB_REF_NAME##chart-}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.RELEASE_HELM_CHART_TOKEN }}
          charts_dir: helm
          charts_url: https://charts.chaos-mesh.org
          owner: chaos-mesh
          repository: charts
          branch: gh-pages
          app_version: ${{ steps.extract_version.outputs.version }}
          chart_version: ${{ steps.extract_version.outputs.version }}
