// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaosdaemon.proto

package pb

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	empty "github.com/golang/protobuf/ptypes/empty"

	context "golang.org/x/net/context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Chain_Direction int32

const (
	Chain_INPUT  Chain_Direction = 0
	Chain_OUTPUT Chain_Direction = 1
)

var Chain_Direction_name = map[int32]string{
	0: "INPUT",
	1: "OUTPUT",
}
var Chain_Direction_value = map[string]int32{
	"INPUT":  0,
	"OUTPUT": 1,
}

func (x Chain_Direction) String() string {
	return proto.EnumName(Chain_Direction_name, int32(x))
}
func (Chain_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{16, 0}
}

type ContainerAction_Action int32

const (
	ContainerAction_KILL   ContainerAction_Action = 0
	ContainerAction_GETPID ContainerAction_Action = 1
)

var ContainerAction_Action_name = map[int32]string{
	0: "KILL",
	1: "GETPID",
}
var ContainerAction_Action_value = map[string]int32{
	"KILL":   0,
	"GETPID": 1,
}

func (x ContainerAction_Action) String() string {
	return proto.EnumName(ContainerAction_Action_name, int32(x))
}
func (ContainerAction_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{18, 0}
}

type ExecStressRequest_Scope int32

const (
	ExecStressRequest_CONTAINER ExecStressRequest_Scope = 0
	ExecStressRequest_POD       ExecStressRequest_Scope = 1
)

var ExecStressRequest_Scope_name = map[int32]string{
	0: "CONTAINER",
	1: "POD",
}
var ExecStressRequest_Scope_value = map[string]int32{
	"CONTAINER": 0,
	"POD":       1,
}

func (x ExecStressRequest_Scope) String() string {
	return proto.EnumName(ExecStressRequest_Scope_name, int32(x))
}
func (ExecStressRequest_Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{19, 0}
}

type TcHandle struct {
	Major                uint32   `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                uint32   `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TcHandle) Reset()         { *m = TcHandle{} }
func (m *TcHandle) String() string { return proto.CompactTextString(m) }
func (*TcHandle) ProtoMessage()    {}
func (*TcHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{0}
}
func (m *TcHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcHandle.Unmarshal(m, b)
}
func (m *TcHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcHandle.Marshal(b, m, deterministic)
}
func (dst *TcHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcHandle.Merge(dst, src)
}
func (m *TcHandle) XXX_Size() int {
	return xxx_messageInfo_TcHandle.Size(m)
}
func (m *TcHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_TcHandle.DiscardUnknown(m)
}

var xxx_messageInfo_TcHandle proto.InternalMessageInfo

func (m *TcHandle) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *TcHandle) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

type ContainerRequest struct {
	Action               *ContainerAction `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ContainerId          string           `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ContainerRequest) Reset()         { *m = ContainerRequest{} }
func (m *ContainerRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerRequest) ProtoMessage()    {}
func (*ContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{1}
}
func (m *ContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRequest.Unmarshal(m, b)
}
func (m *ContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRequest.Marshal(b, m, deterministic)
}
func (dst *ContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRequest.Merge(dst, src)
}
func (m *ContainerRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerRequest.Size(m)
}
func (m *ContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRequest proto.InternalMessageInfo

func (m *ContainerRequest) GetAction() *ContainerAction {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *ContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type ContainerResponse struct {
	Pid                  uint32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerResponse) Reset()         { *m = ContainerResponse{} }
func (m *ContainerResponse) String() string { return proto.CompactTextString(m) }
func (*ContainerResponse) ProtoMessage()    {}
func (*ContainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{2}
}
func (m *ContainerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerResponse.Unmarshal(m, b)
}
func (m *ContainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerResponse.Marshal(b, m, deterministic)
}
func (dst *ContainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerResponse.Merge(dst, src)
}
func (m *ContainerResponse) XXX_Size() int {
	return xxx_messageInfo_ContainerResponse.Size(m)
}
func (m *ContainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerResponse proto.InternalMessageInfo

func (m *ContainerResponse) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type NetemRequest struct {
	Netem                *Netem    `protobuf:"bytes,1,opt,name=netem,proto3" json:"netem,omitempty"`
	ContainerId          string    `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Handle               *TcHandle `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Parent               *TcHandle `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NetemRequest) Reset()         { *m = NetemRequest{} }
func (m *NetemRequest) String() string { return proto.CompactTextString(m) }
func (*NetemRequest) ProtoMessage()    {}
func (*NetemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{3}
}
func (m *NetemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetemRequest.Unmarshal(m, b)
}
func (m *NetemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetemRequest.Marshal(b, m, deterministic)
}
func (dst *NetemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetemRequest.Merge(dst, src)
}
func (m *NetemRequest) XXX_Size() int {
	return xxx_messageInfo_NetemRequest.Size(m)
}
func (m *NetemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NetemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NetemRequest proto.InternalMessageInfo

func (m *NetemRequest) GetNetem() *Netem {
	if m != nil {
		return m.Netem
	}
	return nil
}

func (m *NetemRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *NetemRequest) GetHandle() *TcHandle {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *NetemRequest) GetParent() *TcHandle {
	if m != nil {
		return m.Parent
	}
	return nil
}

type Netem struct {
	Time                 uint32    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Jitter               uint32    `protobuf:"varint,2,opt,name=jitter,proto3" json:"jitter,omitempty"`
	DelayCorr            float32   `protobuf:"fixed32,3,opt,name=delay_corr,json=delayCorr,proto3" json:"delay_corr,omitempty"`
	Limit                uint32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Loss                 float32   `protobuf:"fixed32,5,opt,name=loss,proto3" json:"loss,omitempty"`
	LossCorr             float32   `protobuf:"fixed32,6,opt,name=loss_corr,json=lossCorr,proto3" json:"loss_corr,omitempty"`
	Gap                  uint32    `protobuf:"varint,7,opt,name=gap,proto3" json:"gap,omitempty"`
	Duplicate            float32   `protobuf:"fixed32,8,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	DuplicateCorr        float32   `protobuf:"fixed32,9,opt,name=duplicate_corr,json=duplicateCorr,proto3" json:"duplicate_corr,omitempty"`
	Reorder              float32   `protobuf:"fixed32,10,opt,name=reorder,proto3" json:"reorder,omitempty"`
	ReorderCorr          float32   `protobuf:"fixed32,11,opt,name=reorder_corr,json=reorderCorr,proto3" json:"reorder_corr,omitempty"`
	Corrupt              float32   `protobuf:"fixed32,12,opt,name=corrupt,proto3" json:"corrupt,omitempty"`
	CorruptCorr          float32   `protobuf:"fixed32,13,opt,name=corrupt_corr,json=corruptCorr,proto3" json:"corrupt_corr,omitempty"`
	Parent               *TcHandle `protobuf:"bytes,14,opt,name=parent,proto3" json:"parent,omitempty"`
	Handle               *TcHandle `protobuf:"bytes,15,opt,name=handle,proto3" json:"handle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Netem) Reset()         { *m = Netem{} }
func (m *Netem) String() string { return proto.CompactTextString(m) }
func (*Netem) ProtoMessage()    {}
func (*Netem) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{4}
}
func (m *Netem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Netem.Unmarshal(m, b)
}
func (m *Netem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Netem.Marshal(b, m, deterministic)
}
func (dst *Netem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Netem.Merge(dst, src)
}
func (m *Netem) XXX_Size() int {
	return xxx_messageInfo_Netem.Size(m)
}
func (m *Netem) XXX_DiscardUnknown() {
	xxx_messageInfo_Netem.DiscardUnknown(m)
}

var xxx_messageInfo_Netem proto.InternalMessageInfo

func (m *Netem) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Netem) GetJitter() uint32 {
	if m != nil {
		return m.Jitter
	}
	return 0
}

func (m *Netem) GetDelayCorr() float32 {
	if m != nil {
		return m.DelayCorr
	}
	return 0
}

func (m *Netem) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Netem) GetLoss() float32 {
	if m != nil {
		return m.Loss
	}
	return 0
}

func (m *Netem) GetLossCorr() float32 {
	if m != nil {
		return m.LossCorr
	}
	return 0
}

func (m *Netem) GetGap() uint32 {
	if m != nil {
		return m.Gap
	}
	return 0
}

func (m *Netem) GetDuplicate() float32 {
	if m != nil {
		return m.Duplicate
	}
	return 0
}

func (m *Netem) GetDuplicateCorr() float32 {
	if m != nil {
		return m.DuplicateCorr
	}
	return 0
}

func (m *Netem) GetReorder() float32 {
	if m != nil {
		return m.Reorder
	}
	return 0
}

func (m *Netem) GetReorderCorr() float32 {
	if m != nil {
		return m.ReorderCorr
	}
	return 0
}

func (m *Netem) GetCorrupt() float32 {
	if m != nil {
		return m.Corrupt
	}
	return 0
}

func (m *Netem) GetCorruptCorr() float32 {
	if m != nil {
		return m.CorruptCorr
	}
	return 0
}

func (m *Netem) GetParent() *TcHandle {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Netem) GetHandle() *TcHandle {
	if m != nil {
		return m.Handle
	}
	return nil
}

type TbfRequest struct {
	Tbf                  *Tbf     `protobuf:"bytes,1,opt,name=tbf,proto3" json:"tbf,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TbfRequest) Reset()         { *m = TbfRequest{} }
func (m *TbfRequest) String() string { return proto.CompactTextString(m) }
func (*TbfRequest) ProtoMessage()    {}
func (*TbfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{5}
}
func (m *TbfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TbfRequest.Unmarshal(m, b)
}
func (m *TbfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TbfRequest.Marshal(b, m, deterministic)
}
func (dst *TbfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TbfRequest.Merge(dst, src)
}
func (m *TbfRequest) XXX_Size() int {
	return xxx_messageInfo_TbfRequest.Size(m)
}
func (m *TbfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TbfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TbfRequest proto.InternalMessageInfo

func (m *TbfRequest) GetTbf() *Tbf {
	if m != nil {
		return m.Tbf
	}
	return nil
}

func (m *TbfRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type Tbf struct {
	Rate                 uint64   `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Buffer               uint32   `protobuf:"varint,3,opt,name=buffer,proto3" json:"buffer,omitempty"`
	PeakRate             uint64   `protobuf:"varint,4,opt,name=peak_rate,json=peakRate,proto3" json:"peak_rate,omitempty"`
	MinBurst             uint32   `protobuf:"varint,5,opt,name=min_burst,json=minBurst,proto3" json:"min_burst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tbf) Reset()         { *m = Tbf{} }
func (m *Tbf) String() string { return proto.CompactTextString(m) }
func (*Tbf) ProtoMessage()    {}
func (*Tbf) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{6}
}
func (m *Tbf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tbf.Unmarshal(m, b)
}
func (m *Tbf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tbf.Marshal(b, m, deterministic)
}
func (dst *Tbf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tbf.Merge(dst, src)
}
func (m *Tbf) XXX_Size() int {
	return xxx_messageInfo_Tbf.Size(m)
}
func (m *Tbf) XXX_DiscardUnknown() {
	xxx_messageInfo_Tbf.DiscardUnknown(m)
}

var xxx_messageInfo_Tbf proto.InternalMessageInfo

func (m *Tbf) GetRate() uint64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Tbf) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Tbf) GetBuffer() uint32 {
	if m != nil {
		return m.Buffer
	}
	return 0
}

func (m *Tbf) GetPeakRate() uint64 {
	if m != nil {
		return m.PeakRate
	}
	return 0
}

func (m *Tbf) GetMinBurst() uint32 {
	if m != nil {
		return m.MinBurst
	}
	return 0
}

type QdiscRequest struct {
	Qdisc                *Qdisc   `protobuf:"bytes,1,opt,name=qdisc,proto3" json:"qdisc,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QdiscRequest) Reset()         { *m = QdiscRequest{} }
func (m *QdiscRequest) String() string { return proto.CompactTextString(m) }
func (*QdiscRequest) ProtoMessage()    {}
func (*QdiscRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{7}
}
func (m *QdiscRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QdiscRequest.Unmarshal(m, b)
}
func (m *QdiscRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QdiscRequest.Marshal(b, m, deterministic)
}
func (dst *QdiscRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QdiscRequest.Merge(dst, src)
}
func (m *QdiscRequest) XXX_Size() int {
	return xxx_messageInfo_QdiscRequest.Size(m)
}
func (m *QdiscRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QdiscRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QdiscRequest proto.InternalMessageInfo

func (m *QdiscRequest) GetQdisc() *Qdisc {
	if m != nil {
		return m.Qdisc
	}
	return nil
}

func (m *QdiscRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type Qdisc struct {
	Parent               *TcHandle `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Handle               *TcHandle `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Type                 string    `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Args                 []string  `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Qdisc) Reset()         { *m = Qdisc{} }
func (m *Qdisc) String() string { return proto.CompactTextString(m) }
func (*Qdisc) ProtoMessage()    {}
func (*Qdisc) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{8}
}
func (m *Qdisc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Qdisc.Unmarshal(m, b)
}
func (m *Qdisc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Qdisc.Marshal(b, m, deterministic)
}
func (dst *Qdisc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Qdisc.Merge(dst, src)
}
func (m *Qdisc) XXX_Size() int {
	return xxx_messageInfo_Qdisc.Size(m)
}
func (m *Qdisc) XXX_DiscardUnknown() {
	xxx_messageInfo_Qdisc.DiscardUnknown(m)
}

var xxx_messageInfo_Qdisc proto.InternalMessageInfo

func (m *Qdisc) GetParent() *TcHandle {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Qdisc) GetHandle() *TcHandle {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *Qdisc) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Qdisc) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type EmatchFilterRequest struct {
	Filter               *EmatchFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	ContainerId          string        `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EmatchFilterRequest) Reset()         { *m = EmatchFilterRequest{} }
func (m *EmatchFilterRequest) String() string { return proto.CompactTextString(m) }
func (*EmatchFilterRequest) ProtoMessage()    {}
func (*EmatchFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{9}
}
func (m *EmatchFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmatchFilterRequest.Unmarshal(m, b)
}
func (m *EmatchFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmatchFilterRequest.Marshal(b, m, deterministic)
}
func (dst *EmatchFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmatchFilterRequest.Merge(dst, src)
}
func (m *EmatchFilterRequest) XXX_Size() int {
	return xxx_messageInfo_EmatchFilterRequest.Size(m)
}
func (m *EmatchFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmatchFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmatchFilterRequest proto.InternalMessageInfo

func (m *EmatchFilterRequest) GetFilter() *EmatchFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *EmatchFilterRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type EmatchFilter struct {
	Match                string    `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	Parent               *TcHandle `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Classid              *TcHandle `protobuf:"bytes,3,opt,name=classid,proto3" json:"classid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmatchFilter) Reset()         { *m = EmatchFilter{} }
func (m *EmatchFilter) String() string { return proto.CompactTextString(m) }
func (*EmatchFilter) ProtoMessage()    {}
func (*EmatchFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{10}
}
func (m *EmatchFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmatchFilter.Unmarshal(m, b)
}
func (m *EmatchFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmatchFilter.Marshal(b, m, deterministic)
}
func (dst *EmatchFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmatchFilter.Merge(dst, src)
}
func (m *EmatchFilter) XXX_Size() int {
	return xxx_messageInfo_EmatchFilter.Size(m)
}
func (m *EmatchFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmatchFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EmatchFilter proto.InternalMessageInfo

func (m *EmatchFilter) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func (m *EmatchFilter) GetParent() *TcHandle {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *EmatchFilter) GetClassid() *TcHandle {
	if m != nil {
		return m.Classid
	}
	return nil
}

type TcFilterRequest struct {
	Filter               *TcFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	ContainerId          string    `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TcFilterRequest) Reset()         { *m = TcFilterRequest{} }
func (m *TcFilterRequest) String() string { return proto.CompactTextString(m) }
func (*TcFilterRequest) ProtoMessage()    {}
func (*TcFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{11}
}
func (m *TcFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcFilterRequest.Unmarshal(m, b)
}
func (m *TcFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcFilterRequest.Marshal(b, m, deterministic)
}
func (dst *TcFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcFilterRequest.Merge(dst, src)
}
func (m *TcFilterRequest) XXX_Size() int {
	return xxx_messageInfo_TcFilterRequest.Size(m)
}
func (m *TcFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TcFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TcFilterRequest proto.InternalMessageInfo

func (m *TcFilterRequest) GetFilter() *TcFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *TcFilterRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type TcFilter struct {
	Parent               *TcHandle `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TcFilter) Reset()         { *m = TcFilter{} }
func (m *TcFilter) String() string { return proto.CompactTextString(m) }
func (*TcFilter) ProtoMessage()    {}
func (*TcFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{12}
}
func (m *TcFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TcFilter.Unmarshal(m, b)
}
func (m *TcFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TcFilter.Marshal(b, m, deterministic)
}
func (dst *TcFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TcFilter.Merge(dst, src)
}
func (m *TcFilter) XXX_Size() int {
	return xxx_messageInfo_TcFilter.Size(m)
}
func (m *TcFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_TcFilter.DiscardUnknown(m)
}

var xxx_messageInfo_TcFilter proto.InternalMessageInfo

func (m *TcFilter) GetParent() *TcHandle {
	if m != nil {
		return m.Parent
	}
	return nil
}

type IpSetsRequest struct {
	Ipsets               []*IpSet `protobuf:"bytes,1,rep,name=ipsets,proto3" json:"ipsets,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpSetsRequest) Reset()         { *m = IpSetsRequest{} }
func (m *IpSetsRequest) String() string { return proto.CompactTextString(m) }
func (*IpSetsRequest) ProtoMessage()    {}
func (*IpSetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{13}
}
func (m *IpSetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpSetsRequest.Unmarshal(m, b)
}
func (m *IpSetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpSetsRequest.Marshal(b, m, deterministic)
}
func (dst *IpSetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpSetsRequest.Merge(dst, src)
}
func (m *IpSetsRequest) XXX_Size() int {
	return xxx_messageInfo_IpSetsRequest.Size(m)
}
func (m *IpSetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IpSetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IpSetsRequest proto.InternalMessageInfo

func (m *IpSetsRequest) GetIpsets() []*IpSet {
	if m != nil {
		return m.Ipsets
	}
	return nil
}

func (m *IpSetsRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type IpSet struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cidrs                []string `protobuf:"bytes,2,rep,name=cidrs,proto3" json:"cidrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpSet) Reset()         { *m = IpSet{} }
func (m *IpSet) String() string { return proto.CompactTextString(m) }
func (*IpSet) ProtoMessage()    {}
func (*IpSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{14}
}
func (m *IpSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpSet.Unmarshal(m, b)
}
func (m *IpSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpSet.Marshal(b, m, deterministic)
}
func (dst *IpSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpSet.Merge(dst, src)
}
func (m *IpSet) XXX_Size() int {
	return xxx_messageInfo_IpSet.Size(m)
}
func (m *IpSet) XXX_DiscardUnknown() {
	xxx_messageInfo_IpSet.DiscardUnknown(m)
}

var xxx_messageInfo_IpSet proto.InternalMessageInfo

func (m *IpSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IpSet) GetCidrs() []string {
	if m != nil {
		return m.Cidrs
	}
	return nil
}

type IptablesChainsRequest struct {
	Chains               []*Chain `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	ContainerId          string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IptablesChainsRequest) Reset()         { *m = IptablesChainsRequest{} }
func (m *IptablesChainsRequest) String() string { return proto.CompactTextString(m) }
func (*IptablesChainsRequest) ProtoMessage()    {}
func (*IptablesChainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{15}
}
func (m *IptablesChainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IptablesChainsRequest.Unmarshal(m, b)
}
func (m *IptablesChainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IptablesChainsRequest.Marshal(b, m, deterministic)
}
func (dst *IptablesChainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IptablesChainsRequest.Merge(dst, src)
}
func (m *IptablesChainsRequest) XXX_Size() int {
	return xxx_messageInfo_IptablesChainsRequest.Size(m)
}
func (m *IptablesChainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IptablesChainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IptablesChainsRequest proto.InternalMessageInfo

func (m *IptablesChainsRequest) GetChains() []*Chain {
	if m != nil {
		return m.Chains
	}
	return nil
}

func (m *IptablesChainsRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type Chain struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Direction            Chain_Direction `protobuf:"varint,2,opt,name=direction,proto3,enum=pb.Chain_Direction" json:"direction,omitempty"`
	Ipsets               []string        `protobuf:"bytes,3,rep,name=ipsets,proto3" json:"ipsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{16}
}
func (m *Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chain.Unmarshal(m, b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
}
func (dst *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(dst, src)
}
func (m *Chain) XXX_Size() int {
	return xxx_messageInfo_Chain.Size(m)
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chain) GetDirection() Chain_Direction {
	if m != nil {
		return m.Direction
	}
	return Chain_INPUT
}

func (m *Chain) GetIpsets() []string {
	if m != nil {
		return m.Ipsets
	}
	return nil
}

type TimeRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Sec                  int64    `protobuf:"varint,2,opt,name=sec,proto3" json:"sec,omitempty"`
	Nsec                 int64    `protobuf:"varint,3,opt,name=nsec,proto3" json:"nsec,omitempty"`
	ClkIdsMask           uint64   `protobuf:"varint,4,opt,name=clk_ids_mask,json=clkIdsMask,proto3" json:"clk_ids_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRequest) Reset()         { *m = TimeRequest{} }
func (m *TimeRequest) String() string { return proto.CompactTextString(m) }
func (*TimeRequest) ProtoMessage()    {}
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{17}
}
func (m *TimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRequest.Unmarshal(m, b)
}
func (m *TimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRequest.Marshal(b, m, deterministic)
}
func (dst *TimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRequest.Merge(dst, src)
}
func (m *TimeRequest) XXX_Size() int {
	return xxx_messageInfo_TimeRequest.Size(m)
}
func (m *TimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRequest proto.InternalMessageInfo

func (m *TimeRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *TimeRequest) GetSec() int64 {
	if m != nil {
		return m.Sec
	}
	return 0
}

func (m *TimeRequest) GetNsec() int64 {
	if m != nil {
		return m.Nsec
	}
	return 0
}

func (m *TimeRequest) GetClkIdsMask() uint64 {
	if m != nil {
		return m.ClkIdsMask
	}
	return 0
}

type ContainerAction struct {
	Action               ContainerAction_Action `protobuf:"varint,1,opt,name=action,proto3,enum=pb.ContainerAction_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ContainerAction) Reset()         { *m = ContainerAction{} }
func (m *ContainerAction) String() string { return proto.CompactTextString(m) }
func (*ContainerAction) ProtoMessage()    {}
func (*ContainerAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{18}
}
func (m *ContainerAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerAction.Unmarshal(m, b)
}
func (m *ContainerAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerAction.Marshal(b, m, deterministic)
}
func (dst *ContainerAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerAction.Merge(dst, src)
}
func (m *ContainerAction) XXX_Size() int {
	return xxx_messageInfo_ContainerAction.Size(m)
}
func (m *ContainerAction) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerAction.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerAction proto.InternalMessageInfo

func (m *ContainerAction) GetAction() ContainerAction_Action {
	if m != nil {
		return m.Action
	}
	return ContainerAction_KILL
}

type ExecStressRequest struct {
	Scope                ExecStressRequest_Scope `protobuf:"varint,1,opt,name=scope,proto3,enum=pb.ExecStressRequest_Scope" json:"scope,omitempty"`
	Target               string                  `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Stressors            string                  `protobuf:"bytes,3,opt,name=stressors,proto3" json:"stressors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExecStressRequest) Reset()         { *m = ExecStressRequest{} }
func (m *ExecStressRequest) String() string { return proto.CompactTextString(m) }
func (*ExecStressRequest) ProtoMessage()    {}
func (*ExecStressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{19}
}
func (m *ExecStressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecStressRequest.Unmarshal(m, b)
}
func (m *ExecStressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecStressRequest.Marshal(b, m, deterministic)
}
func (dst *ExecStressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecStressRequest.Merge(dst, src)
}
func (m *ExecStressRequest) XXX_Size() int {
	return xxx_messageInfo_ExecStressRequest.Size(m)
}
func (m *ExecStressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecStressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecStressRequest proto.InternalMessageInfo

func (m *ExecStressRequest) GetScope() ExecStressRequest_Scope {
	if m != nil {
		return m.Scope
	}
	return ExecStressRequest_CONTAINER
}

func (m *ExecStressRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ExecStressRequest) GetStressors() string {
	if m != nil {
		return m.Stressors
	}
	return ""
}

type ExecStressResponse struct {
	Instance             string   `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecStressResponse) Reset()         { *m = ExecStressResponse{} }
func (m *ExecStressResponse) String() string { return proto.CompactTextString(m) }
func (*ExecStressResponse) ProtoMessage()    {}
func (*ExecStressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{20}
}
func (m *ExecStressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecStressResponse.Unmarshal(m, b)
}
func (m *ExecStressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecStressResponse.Marshal(b, m, deterministic)
}
func (dst *ExecStressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecStressResponse.Merge(dst, src)
}
func (m *ExecStressResponse) XXX_Size() int {
	return xxx_messageInfo_ExecStressResponse.Size(m)
}
func (m *ExecStressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecStressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecStressResponse proto.InternalMessageInfo

func (m *ExecStressResponse) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *ExecStressResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

type CancelStressRequest struct {
	Instance             string   `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelStressRequest) Reset()         { *m = CancelStressRequest{} }
func (m *CancelStressRequest) String() string { return proto.CompactTextString(m) }
func (*CancelStressRequest) ProtoMessage()    {}
func (*CancelStressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chaosdaemon_9fdbad378bfed646, []int{21}
}
func (m *CancelStressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelStressRequest.Unmarshal(m, b)
}
func (m *CancelStressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelStressRequest.Marshal(b, m, deterministic)
}
func (dst *CancelStressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelStressRequest.Merge(dst, src)
}
func (m *CancelStressRequest) XXX_Size() int {
	return xxx_messageInfo_CancelStressRequest.Size(m)
}
func (m *CancelStressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelStressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelStressRequest proto.InternalMessageInfo

func (m *CancelStressRequest) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *CancelStressRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func init() {
	proto.RegisterType((*TcHandle)(nil), "pb.TcHandle")
	proto.RegisterType((*ContainerRequest)(nil), "pb.ContainerRequest")
	proto.RegisterType((*ContainerResponse)(nil), "pb.ContainerResponse")
	proto.RegisterType((*NetemRequest)(nil), "pb.NetemRequest")
	proto.RegisterType((*Netem)(nil), "pb.Netem")
	proto.RegisterType((*TbfRequest)(nil), "pb.TbfRequest")
	proto.RegisterType((*Tbf)(nil), "pb.Tbf")
	proto.RegisterType((*QdiscRequest)(nil), "pb.QdiscRequest")
	proto.RegisterType((*Qdisc)(nil), "pb.Qdisc")
	proto.RegisterType((*EmatchFilterRequest)(nil), "pb.EmatchFilterRequest")
	proto.RegisterType((*EmatchFilter)(nil), "pb.EmatchFilter")
	proto.RegisterType((*TcFilterRequest)(nil), "pb.TcFilterRequest")
	proto.RegisterType((*TcFilter)(nil), "pb.TcFilter")
	proto.RegisterType((*IpSetsRequest)(nil), "pb.IpSetsRequest")
	proto.RegisterType((*IpSet)(nil), "pb.IpSet")
	proto.RegisterType((*IptablesChainsRequest)(nil), "pb.IptablesChainsRequest")
	proto.RegisterType((*Chain)(nil), "pb.Chain")
	proto.RegisterType((*TimeRequest)(nil), "pb.TimeRequest")
	proto.RegisterType((*ContainerAction)(nil), "pb.ContainerAction")
	proto.RegisterType((*ExecStressRequest)(nil), "pb.ExecStressRequest")
	proto.RegisterType((*ExecStressResponse)(nil), "pb.ExecStressResponse")
	proto.RegisterType((*CancelStressRequest)(nil), "pb.CancelStressRequest")
	proto.RegisterEnum("pb.Chain_Direction", Chain_Direction_name, Chain_Direction_value)
	proto.RegisterEnum("pb.ContainerAction_Action", ContainerAction_Action_name, ContainerAction_Action_value)
	proto.RegisterEnum("pb.ExecStressRequest_Scope", ExecStressRequest_Scope_name, ExecStressRequest_Scope_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaosDaemonClient is the client API for ChaosDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaosDaemonClient interface {
	SetNetem(ctx context.Context, in *NetemRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteNetem(ctx context.Context, in *NetemRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetTbf(ctx context.Context, in *TbfRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteTbf(ctx context.Context, in *TbfRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AddQdisc(ctx context.Context, in *QdiscRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DelQdisc(ctx context.Context, in *QdiscRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	AddEmatchFilter(ctx context.Context, in *EmatchFilterRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// generic tc filter del command
	DelTcFilter(ctx context.Context, in *TcFilterRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	FlushIpSets(ctx context.Context, in *IpSetsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	FlushIptablesChains(ctx context.Context, in *IptablesChainsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	SetTimeOffset(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RecoverTimeOffset(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ContainerKill(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ContainerGetPid(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*ContainerResponse, error)
	ExecStressors(ctx context.Context, in *ExecStressRequest, opts ...grpc.CallOption) (*ExecStressResponse, error)
	CancelStressors(ctx context.Context, in *CancelStressRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type chaosDaemonClient struct {
	cc *grpc.ClientConn
}

func NewChaosDaemonClient(cc *grpc.ClientConn) ChaosDaemonClient {
	return &chaosDaemonClient{cc}
}

func (c *chaosDaemonClient) SetNetem(ctx context.Context, in *NetemRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/SetNetem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) DeleteNetem(ctx context.Context, in *NetemRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/DeleteNetem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) SetTbf(ctx context.Context, in *TbfRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/SetTbf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) DeleteTbf(ctx context.Context, in *TbfRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/DeleteTbf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) AddQdisc(ctx context.Context, in *QdiscRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/AddQdisc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) DelQdisc(ctx context.Context, in *QdiscRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/DelQdisc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) AddEmatchFilter(ctx context.Context, in *EmatchFilterRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/AddEmatchFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) DelTcFilter(ctx context.Context, in *TcFilterRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/DelTcFilter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) FlushIpSets(ctx context.Context, in *IpSetsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/FlushIpSets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) FlushIptablesChains(ctx context.Context, in *IptablesChainsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/FlushIptablesChains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) SetTimeOffset(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/SetTimeOffset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) RecoverTimeOffset(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/RecoverTimeOffset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) ContainerKill(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/ContainerKill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) ContainerGetPid(ctx context.Context, in *ContainerRequest, opts ...grpc.CallOption) (*ContainerResponse, error) {
	out := new(ContainerResponse)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/ContainerGetPid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) ExecStressors(ctx context.Context, in *ExecStressRequest, opts ...grpc.CallOption) (*ExecStressResponse, error) {
	out := new(ExecStressResponse)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/ExecStressors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosDaemonClient) CancelStressors(ctx context.Context, in *CancelStressRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ChaosDaemon/CancelStressors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaosDaemonServer is the server API for ChaosDaemon service.
type ChaosDaemonServer interface {
	SetNetem(context.Context, *NetemRequest) (*empty.Empty, error)
	DeleteNetem(context.Context, *NetemRequest) (*empty.Empty, error)
	SetTbf(context.Context, *TbfRequest) (*empty.Empty, error)
	DeleteTbf(context.Context, *TbfRequest) (*empty.Empty, error)
	AddQdisc(context.Context, *QdiscRequest) (*empty.Empty, error)
	DelQdisc(context.Context, *QdiscRequest) (*empty.Empty, error)
	AddEmatchFilter(context.Context, *EmatchFilterRequest) (*empty.Empty, error)
	// generic tc filter del command
	DelTcFilter(context.Context, *TcFilterRequest) (*empty.Empty, error)
	FlushIpSets(context.Context, *IpSetsRequest) (*empty.Empty, error)
	FlushIptablesChains(context.Context, *IptablesChainsRequest) (*empty.Empty, error)
	SetTimeOffset(context.Context, *TimeRequest) (*empty.Empty, error)
	RecoverTimeOffset(context.Context, *TimeRequest) (*empty.Empty, error)
	ContainerKill(context.Context, *ContainerRequest) (*empty.Empty, error)
	ContainerGetPid(context.Context, *ContainerRequest) (*ContainerResponse, error)
	ExecStressors(context.Context, *ExecStressRequest) (*ExecStressResponse, error)
	CancelStressors(context.Context, *CancelStressRequest) (*empty.Empty, error)
}

func RegisterChaosDaemonServer(s *grpc.Server, srv ChaosDaemonServer) {
	s.RegisterService(&_ChaosDaemon_serviceDesc, srv)
}

func _ChaosDaemon_SetNetem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).SetNetem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/SetNetem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).SetNetem(ctx, req.(*NetemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_DeleteNetem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).DeleteNetem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/DeleteNetem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).DeleteNetem(ctx, req.(*NetemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_SetTbf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TbfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).SetTbf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/SetTbf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).SetTbf(ctx, req.(*TbfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_DeleteTbf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TbfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).DeleteTbf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/DeleteTbf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).DeleteTbf(ctx, req.(*TbfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_AddQdisc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QdiscRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).AddQdisc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/AddQdisc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).AddQdisc(ctx, req.(*QdiscRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_DelQdisc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QdiscRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).DelQdisc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/DelQdisc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).DelQdisc(ctx, req.(*QdiscRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_AddEmatchFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmatchFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).AddEmatchFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/AddEmatchFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).AddEmatchFilter(ctx, req.(*EmatchFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_DelTcFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TcFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).DelTcFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/DelTcFilter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).DelTcFilter(ctx, req.(*TcFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_FlushIpSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).FlushIpSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/FlushIpSets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).FlushIpSets(ctx, req.(*IpSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_FlushIptablesChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IptablesChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).FlushIptablesChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/FlushIptablesChains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).FlushIptablesChains(ctx, req.(*IptablesChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_SetTimeOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).SetTimeOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/SetTimeOffset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).SetTimeOffset(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_RecoverTimeOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).RecoverTimeOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/RecoverTimeOffset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).RecoverTimeOffset(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_ContainerKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).ContainerKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/ContainerKill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).ContainerKill(ctx, req.(*ContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_ContainerGetPid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).ContainerGetPid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/ContainerGetPid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).ContainerGetPid(ctx, req.(*ContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_ExecStressors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecStressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).ExecStressors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/ExecStressors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).ExecStressors(ctx, req.(*ExecStressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosDaemon_CancelStressors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelStressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosDaemonServer).CancelStressors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ChaosDaemon/CancelStressors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosDaemonServer).CancelStressors(ctx, req.(*CancelStressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChaosDaemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ChaosDaemon",
	HandlerType: (*ChaosDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetNetem",
			Handler:    _ChaosDaemon_SetNetem_Handler,
		},
		{
			MethodName: "DeleteNetem",
			Handler:    _ChaosDaemon_DeleteNetem_Handler,
		},
		{
			MethodName: "SetTbf",
			Handler:    _ChaosDaemon_SetTbf_Handler,
		},
		{
			MethodName: "DeleteTbf",
			Handler:    _ChaosDaemon_DeleteTbf_Handler,
		},
		{
			MethodName: "AddQdisc",
			Handler:    _ChaosDaemon_AddQdisc_Handler,
		},
		{
			MethodName: "DelQdisc",
			Handler:    _ChaosDaemon_DelQdisc_Handler,
		},
		{
			MethodName: "AddEmatchFilter",
			Handler:    _ChaosDaemon_AddEmatchFilter_Handler,
		},
		{
			MethodName: "DelTcFilter",
			Handler:    _ChaosDaemon_DelTcFilter_Handler,
		},
		{
			MethodName: "FlushIpSets",
			Handler:    _ChaosDaemon_FlushIpSets_Handler,
		},
		{
			MethodName: "FlushIptablesChains",
			Handler:    _ChaosDaemon_FlushIptablesChains_Handler,
		},
		{
			MethodName: "SetTimeOffset",
			Handler:    _ChaosDaemon_SetTimeOffset_Handler,
		},
		{
			MethodName: "RecoverTimeOffset",
			Handler:    _ChaosDaemon_RecoverTimeOffset_Handler,
		},
		{
			MethodName: "ContainerKill",
			Handler:    _ChaosDaemon_ContainerKill_Handler,
		},
		{
			MethodName: "ContainerGetPid",
			Handler:    _ChaosDaemon_ContainerGetPid_Handler,
		},
		{
			MethodName: "ExecStressors",
			Handler:    _ChaosDaemon_ExecStressors_Handler,
		},
		{
			MethodName: "CancelStressors",
			Handler:    _ChaosDaemon_CancelStressors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chaosdaemon.proto",
}

func init() { proto.RegisterFile("chaosdaemon.proto", fileDescriptor_chaosdaemon_9fdbad378bfed646) }

var fileDescriptor_chaosdaemon_9fdbad378bfed646 = []byte{
	// 1266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xef, 0x6e, 0x1b, 0x45,
	0x10, 0xaf, 0x7d, 0xb1, 0xe3, 0x1b, 0xdb, 0xb1, 0xb3, 0x69, 0xc3, 0x35, 0x01, 0x9a, 0x9e, 0x5a,
	0x54, 0x09, 0xc9, 0xa5, 0x41, 0x54, 0x02, 0x21, 0x20, 0xd8, 0x69, 0x71, 0x5b, 0x92, 0x70, 0x71,
	0xbf, 0x20, 0x21, 0xeb, 0xfe, 0xac, 0xed, 0x6d, 0xee, 0x5f, 0x6f, 0xd7, 0xa8, 0x11, 0x9f, 0xf8,
	0xca, 0x3b, 0xc0, 0x63, 0xf0, 0x58, 0x3c, 0x03, 0xda, 0xd9, 0x3d, 0xfb, 0x9c, 0x3a, 0x89, 0xd3,
	0x4f, 0xb7, 0xf3, 0x9b, 0xf9, 0xcd, 0xce, 0xec, 0xdc, 0xce, 0x2c, 0x6c, 0xfa, 0x13, 0x37, 0xe1,
	0x81, 0x4b, 0xa3, 0x24, 0xee, 0xa4, 0x59, 0x22, 0x12, 0x52, 0x4e, 0xbd, 0x9d, 0xdd, 0x71, 0x92,
	0x8c, 0x43, 0xfa, 0x18, 0x11, 0x6f, 0x3a, 0x7a, 0x4c, 0xa3, 0x54, 0x9c, 0x2b, 0x03, 0xfb, 0x29,
	0xd4, 0x06, 0xfe, 0x4f, 0x6e, 0x1c, 0x84, 0x94, 0xdc, 0x86, 0x4a, 0xe4, 0xbe, 0x49, 0x32, 0xab,
	0xb4, 0x57, 0x7a, 0xd4, 0x74, 0x94, 0x80, 0x28, 0x8b, 0x93, 0xcc, 0x2a, 0x6b, 0x54, 0x0a, 0xb6,
	0x07, 0xed, 0x6e, 0x12, 0x0b, 0x97, 0xc5, 0x34, 0x73, 0xe8, 0xdb, 0x29, 0xe5, 0x82, 0x7c, 0x0e,
	0x55, 0xd7, 0x17, 0x2c, 0x89, 0xd1, 0x41, 0x7d, 0x7f, 0xab, 0x93, 0x7a, 0x9d, 0x99, 0xd5, 0x01,
	0xaa, 0x1c, 0x6d, 0x42, 0xee, 0x43, 0xc3, 0xcf, 0x55, 0x43, 0x16, 0xa0, 0x77, 0xd3, 0xa9, 0xcf,
	0xb0, 0x7e, 0x60, 0x3f, 0x84, 0xcd, 0xc2, 0x1e, 0x3c, 0x4d, 0x62, 0x4e, 0x49, 0x1b, 0x8c, 0x94,
	0x05, 0x3a, 0x44, 0xb9, 0xb4, 0xff, 0x29, 0x41, 0xe3, 0x88, 0x0a, 0x1a, 0xe5, 0x71, 0xdc, 0x83,
	0x4a, 0x2c, 0x65, 0x1d, 0x86, 0x29, 0xc3, 0x50, 0x06, 0x0a, 0x5f, 0x61, 0x6f, 0xf2, 0x00, 0xaa,
	0x13, 0x3c, 0x15, 0xcb, 0x40, 0x27, 0x0d, 0xe9, 0x24, 0x3f, 0x29, 0x47, 0xeb, 0xa4, 0x55, 0xea,
	0x66, 0x34, 0x16, 0xd6, 0xda, 0x32, 0x2b, 0xa5, 0xb3, 0xff, 0x35, 0xa0, 0x82, 0xfb, 0x13, 0x02,
	0x6b, 0x82, 0x45, 0x54, 0x47, 0x8f, 0x6b, 0xb2, 0x0d, 0xd5, 0x37, 0x4c, 0x08, 0x9a, 0x1f, 0xb0,
	0x96, 0xc8, 0x27, 0x00, 0x01, 0x0d, 0xdd, 0xf3, 0xa1, 0x9f, 0x64, 0x19, 0x46, 0x51, 0x76, 0x4c,
	0x44, 0xba, 0x49, 0x86, 0x65, 0x09, 0x59, 0xc4, 0xd4, 0xce, 0x4d, 0x47, 0x09, 0x72, 0x83, 0x30,
	0xe1, 0xdc, 0xaa, 0xa0, 0x39, 0xae, 0xc9, 0x2e, 0x98, 0xf2, 0xab, 0xfc, 0x54, 0x51, 0x51, 0x93,
	0x00, 0xba, 0x69, 0x83, 0x31, 0x76, 0x53, 0x6b, 0x5d, 0x1d, 0xe7, 0xd8, 0x4d, 0xc9, 0xc7, 0x60,
	0x06, 0xd3, 0x34, 0x64, 0xbe, 0x2b, 0xa8, 0x55, 0xd3, 0xdb, 0xe6, 0x00, 0x79, 0x08, 0x1b, 0x33,
	0x41, 0x79, 0x34, 0xd1, 0xa4, 0x39, 0x43, 0xd1, 0xad, 0x05, 0xeb, 0x19, 0x4d, 0xb2, 0x80, 0x66,
	0x16, 0xa0, 0x3e, 0x17, 0xe5, 0xd9, 0xeb, 0xa5, 0xa2, 0xd7, 0x51, 0x5d, 0xd7, 0x58, 0x4e, 0x96,
	0xaa, 0x69, 0x2a, 0xac, 0x86, 0x22, 0x6b, 0x51, 0x15, 0x0e, 0x97, 0x8a, 0xdc, 0x54, 0x64, 0x8d,
	0x21, 0x79, 0x5e, 0x92, 0x8d, 0xcb, 0x4b, 0x52, 0x28, 0x6f, 0xeb, 0xf2, 0xf2, 0xda, 0x2f, 0x00,
	0x06, 0xde, 0x28, 0xff, 0xad, 0xee, 0x82, 0x21, 0xbc, 0x91, 0xfe, 0xa9, 0xd6, 0x91, 0xe0, 0x8d,
	0x1c, 0x89, 0xad, 0xf2, 0x33, 0xff, 0x59, 0x02, 0x63, 0xe0, 0x8d, 0x64, 0x85, 0x32, 0x79, 0xb2,
	0xd2, 0xcd, 0x9a, 0x83, 0xeb, 0x79, 0x2d, 0xcb, 0xc5, 0x5a, 0x6e, 0x43, 0xd5, 0x9b, 0x8e, 0x46,
	0x54, 0x15, 0xbf, 0xe9, 0x68, 0x49, 0xd6, 0x33, 0xa5, 0xee, 0xd9, 0x10, 0xdd, 0xac, 0xa1, 0x9b,
	0x9a, 0x04, 0x1c, 0xe9, 0x6a, 0x17, 0xcc, 0x88, 0xc5, 0x43, 0x6f, 0x9a, 0x71, 0x81, 0x7f, 0x41,
	0xd3, 0xa9, 0x45, 0x2c, 0xfe, 0x51, 0xca, 0xb6, 0x03, 0x8d, 0x5f, 0x02, 0xc6, 0xfd, 0xc2, 0x45,
	0x79, 0x2b, 0xe5, 0xe2, 0x45, 0x51, 0x06, 0x0a, 0x5f, 0x25, 0xaf, 0x3f, 0xa0, 0x82, 0x94, 0xc2,
	0xc1, 0x97, 0x56, 0x3a, 0xf8, 0xf2, 0x15, 0xf7, 0x4a, 0xde, 0x93, 0xf3, 0x54, 0xdd, 0x3d, 0xd3,
	0xc1, 0xb5, 0xc4, 0xdc, 0x6c, 0xcc, 0xad, 0xb5, 0x3d, 0x43, 0x62, 0x72, 0x6d, 0x7b, 0xb0, 0x75,
	0x18, 0xb9, 0xc2, 0x9f, 0x3c, 0x63, 0xa1, 0x98, 0x37, 0xa2, 0x47, 0x50, 0x1d, 0x21, 0xa0, 0x43,
	0x69, 0xcb, 0x4d, 0x16, 0x0c, 0xb5, 0x7e, 0x95, 0x04, 0x33, 0x68, 0x14, 0xa9, 0xaa, 0x4b, 0x0a,
	0x7f, 0x82, 0xbe, 0x4d, 0x47, 0x09, 0x85, 0xec, 0xcb, 0x57, 0x64, 0xff, 0x19, 0xac, 0xfb, 0xa1,
	0xcb, 0x39, 0x0b, 0x96, 0xb6, 0x95, 0x5c, 0x69, 0xff, 0x0a, 0xad, 0x81, 0xbf, 0x98, 0xd3, 0x83,
	0x0b, 0x39, 0x69, 0xe6, 0xcd, 0xf3, 0xf9, 0x42, 0x76, 0x7c, 0x9d, 0xcb, 0x4a, 0x35, 0xb3, 0x5f,
	0x43, 0xb3, 0x9f, 0x9e, 0x52, 0xc1, 0xf3, 0x58, 0xee, 0x43, 0x95, 0xa5, 0x9c, 0x0a, 0x6e, 0x95,
	0xf6, 0x8c, 0xfc, 0xc7, 0x41, 0x13, 0x47, 0x2b, 0x56, 0x09, 0xe4, 0x09, 0x54, 0x90, 0x23, 0x2b,
	0x1b, 0xbb, 0xba, 0x2b, 0x9a, 0x0e, 0xae, 0xe5, 0x29, 0xfb, 0x2c, 0xc8, 0xb8, 0x55, 0xc6, 0x72,
	0x2b, 0xc1, 0xfe, 0x0d, 0xee, 0xf4, 0x53, 0xe1, 0x7a, 0x21, 0xe5, 0xdd, 0x89, 0xcb, 0xe2, 0x62,
	0x44, 0x3e, 0x02, 0xc5, 0x88, 0xd0, 0xc4, 0xd1, 0x8a, 0x55, 0x22, 0xfa, 0xab, 0x04, 0x15, 0x24,
	0x2d, 0x0d, 0xe9, 0x09, 0x98, 0x01, 0xcb, 0xa8, 0x9a, 0x70, 0x92, 0xbd, 0xa1, 0x27, 0x9c, 0x64,
	0x74, 0x7a, 0xb9, 0xca, 0x99, 0x5b, 0xc9, 0x2b, 0xac, 0x0f, 0xca, 0xc0, 0x34, 0xb4, 0x64, 0xdb,
	0x60, 0xce, 0xec, 0x89, 0x09, 0x95, 0xfe, 0xd1, 0xc9, 0xeb, 0x41, 0xfb, 0x16, 0x01, 0xa8, 0x1e,
	0xbf, 0x1e, 0xc8, 0x75, 0xc9, 0x7e, 0x07, 0xf5, 0x01, 0x8b, 0xe8, 0x3c, 0xc3, 0xc5, 0xf0, 0x4b,
	0xef, 0xcf, 0xac, 0x36, 0x18, 0x9c, 0xfa, 0x18, 0x9a, 0xe1, 0xc8, 0x25, 0xa6, 0x21, 0x21, 0x03,
	0x21, 0x5c, 0x93, 0x3d, 0x68, 0xf8, 0xe1, 0xd9, 0x90, 0x05, 0x7c, 0x18, 0xb9, 0xfc, 0x4c, 0x77,
	0x10, 0xf0, 0xc3, 0xb3, 0x7e, 0xc0, 0x7f, 0x76, 0xf9, 0x99, 0x4d, 0xa1, 0x75, 0x61, 0x6a, 0x93,
	0xfd, 0x85, 0xd1, 0xbe, 0xb1, 0xbf, 0xb3, 0x64, 0xb4, 0x77, 0x16, 0x27, 0xbc, 0xfd, 0x29, 0x54,
	0x35, 0xbb, 0x06, 0x6b, 0x2f, 0xfb, 0xaf, 0x5e, 0xa9, 0x04, 0x9f, 0x1f, 0x0e, 0x4e, 0xfa, 0xbd,
	0x76, 0xc9, 0xfe, 0xbb, 0x04, 0x9b, 0x87, 0xef, 0xa8, 0x7f, 0x2a, 0x32, 0xca, 0x67, 0x95, 0x7c,
	0x02, 0x15, 0xee, 0x27, 0x29, 0xd5, 0x1b, 0xed, 0xe2, 0xd5, 0xbd, 0x68, 0xd5, 0x39, 0x95, 0x26,
	0x8e, 0xb2, 0x94, 0xa7, 0x2c, 0xdc, 0x6c, 0x4c, 0x85, 0xae, 0xa9, 0x96, 0xe4, 0x24, 0xe3, 0xc8,
	0x4a, 0x32, 0xae, 0x5b, 0xc9, 0x1c, 0xb0, 0xef, 0x41, 0x05, 0xbd, 0x90, 0x26, 0x98, 0xdd, 0xe3,
	0xa3, 0xc1, 0x41, 0xff, 0xe8, 0xd0, 0x69, 0xdf, 0x22, 0xeb, 0x60, 0x9c, 0x1c, 0xcb, 0xf8, 0x8e,
	0x80, 0x14, 0x37, 0xd6, 0xef, 0x8f, 0x1d, 0xa8, 0xb1, 0x98, 0x0b, 0x37, 0xf6, 0xf3, 0xbf, 0x63,
	0x26, 0xab, 0x0d, 0xdd, 0x4c, 0xc8, 0xba, 0xe9, 0x32, 0xcc, 0x01, 0xfb, 0x18, 0xb6, 0xba, 0xd2,
	0x2c, 0x5c, 0x4c, 0xf8, 0x83, 0x1d, 0xee, 0xff, 0xb7, 0x0e, 0xf5, 0xae, 0x7c, 0xf2, 0xf5, 0xf0,
	0xc9, 0x47, 0x9e, 0x42, 0xed, 0x94, 0x0a, 0xf5, 0xd2, 0x68, 0xcf, 0x1f, 0x3d, 0x6a, 0x9f, 0x9d,
	0xed, 0x8e, 0x7a, 0x07, 0x76, 0xf2, 0x77, 0x60, 0xe7, 0x50, 0xbe, 0x03, 0xed, 0x5b, 0xe4, 0x6b,
	0xa8, 0xf7, 0x68, 0x48, 0x05, 0xbd, 0x39, 0x75, 0x1f, 0xaa, 0xa7, 0x54, 0xc8, 0xb9, 0xb6, 0x91,
	0x0f, 0xc4, 0x6b, 0x39, 0x5f, 0x81, 0xa9, 0xb6, 0xbb, 0x19, 0xed, 0x29, 0xd4, 0x0e, 0x82, 0x40,
	0xcd, 0x9a, 0xf6, 0x7c, 0x52, 0xad, 0xc2, 0xeb, 0xd1, 0xf0, 0xe6, 0xbc, 0x1e, 0xb4, 0x0e, 0x82,
	0x60, 0xa1, 0xf5, 0x7f, 0xf4, 0xde, 0x1c, 0xb9, 0xd6, 0xcb, 0xb7, 0x78, 0xb6, 0xb3, 0x86, 0xbb,
	0xb5, 0xd0, 0xb5, 0xaf, 0x65, 0x7f, 0x03, 0xf5, 0x67, 0xe1, 0x94, 0x4f, 0x54, 0xfb, 0x25, 0x9b,
	0xb3, 0x3e, 0xcb, 0xaf, 0xe7, 0xbe, 0x80, 0x2d, 0xcd, 0x2d, 0x36, 0x4c, 0x72, 0x57, 0xf9, 0x58,
	0xd2, 0x44, 0xaf, 0x8c, 0xa3, 0x29, 0xcb, 0xcc, 0x22, 0x7a, 0x3c, 0x1a, 0x71, 0x2a, 0x48, 0x0b,
	0xf3, 0x98, 0xb7, 0xa7, 0x2b, 0xb8, 0xdf, 0xc1, 0xa6, 0x43, 0xfd, 0xe4, 0x77, 0x9a, 0x7d, 0x18,
	0xff, 0x7b, 0x68, 0xce, 0x1a, 0xcd, 0x4b, 0x16, 0x86, 0xe4, 0xf6, 0x42, 0xef, 0xb9, 0xde, 0xc1,
	0x0f, 0x85, 0x76, 0xf6, 0x9c, 0x8a, 0x13, 0x16, 0x5c, 0xe2, 0xe2, 0xce, 0x05, 0x54, 0xdd, 0x78,
	0xf4, 0xd0, 0x9c, 0x77, 0x82, 0x24, 0xe3, 0xe4, 0xce, 0xd2, 0xae, 0xb4, 0xb3, 0x7d, 0x11, 0x9e,
	0x79, 0xe8, 0x41, 0xab, 0x78, 0xf7, 0xa5, 0x0f, 0xfc, 0x99, 0x96, 0x34, 0x84, 0xcb, 0x33, 0xf1,
	0xaa, 0x88, 0x7c, 0xf9, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0x20, 0xa6, 0x79, 0xe9, 0x0d,
	0x00, 0x00,
}
